---
- hosts: wordpress
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

  #################################
  ## setup the user, the domain, the database
  #################################
  - name: ensure user exists
    hsuser.js: name="{{pac}}-{{user}}" password="{{password}}" exists="true"
  - name: setup domain
    hsdomain.js: name="{{domain}}" owner="{{pac}}-{{user}}" exists="true"
  - name: setup database
    hsdatabase.js: name="{{pac}}_{{user}}" password="{{password}}" instance="mysql" exists="true"

  - name: Sleep to avoid issue invalid user for temporary files
    pause:
      seconds: 10

  #################################
  ## install useful helper script
  #################################
  - name: create bin directory
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
      path: "/home/pacs/{{pac}}/users/{{user}}/bin"
      state: directory
      mode: 0744

  - name: download wp-cli
    become: yes
    become_user: "{{pac}}-{{user}}"
    get_url:
      # see https://wp-cli.org
      url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
      dest: /home/pacs/{{pac}}/users/{{user}}/bin/wp-cli.phar
      mode: '0700'

  #################################
  ## install wordpress
  #################################
  - name: install wordpress
    become: yes
    become_user: "{{pac}}-{{user}}"
    unarchive:
      creates: /home/pacs/{{pac}}/users/{{user}}/wordpress
      src: https://de.wordpress.org/latest-de_DE.tar.gz
      remote_src: yes
      dest: /home/pacs/{{pac}}/users/{{user}}

  - name: drop htdocs-ssl
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
       path: "/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/htdocs-ssl"
       state: absent

  - name: create symbolic link for htdocs-ssl
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
      src: "/home/pacs/{{pac}}/users/{{user}}/wordpress"
      dest: "/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/htdocs-ssl"
      state: link

  #################################
  ## prepare configuration file
  #################################
  - name: copy config file
    become: yes
    become_user: "{{pac}}-{{user}}"
    copy:
      src: "/home/pacs/{{pac}}/users/{{user}}/wordpress/wp-config-sample.php"
      remote_src: yes
      dest: "/home/pacs/{{pac}}/users/{{user}}/wordpress/wp-config.php"
  - name: set user name
    become: yes
    become_user: "{{pac}}-{{user}}"
    lineinfile:
      path: "/home/pacs/{{pac}}/users/{{user}}/wordpress/wp-config.php"
      regexp: '^define\( ''DB_USER'','
      line: "define( 'DB_USER', '{{pac}}_{{user}}' );"
  - name: set database name
    become: yes
    become_user: "{{pac}}-{{user}}"
    lineinfile:
      path: "/home/pacs/{{pac}}/users/{{user}}/wordpress/wp-config.php"
      regexp: '^define\( ''DB_NAME'','
      line: "define( 'DB_NAME', '{{pac}}_{{user}}' );"
  - name: set database password
    become: yes
    become_user: "{{pac}}-{{user}}"
    lineinfile:
      path: "/home/pacs/{{pac}}/users/{{user}}/wordpress/wp-config.php"
      regexp: '^define\( ''DB_PASSWORD'','
      line: "define( 'DB_PASSWORD', '{{password}}' );"
  - name: set keys and salts
    become: yes
    become_user: "{{pac}}-{{user}}"
    shell: |
      secret=`openssl rand -base64 64 | tr -d '\n'`
      sed -i "s#'AUTH_KEY',.*#'AUTH_KEY', '$secret');#g" wp-config.php
      secret=`openssl rand -base64 64 | tr -d '\n'`
      sed -i "s#'SECURE_AUTH_KEY',.*#'SECURE_AUTH_KEY', '$secret');#g" wp-config.php
      secret=`openssl rand -base64 64 | tr -d '\n'`
      sed -i "s#'LOGGED_IN_KEY',.*#'LOGGED_IN_KEY', '$secret');#g" wp-config.php
      secret=`openssl rand -base64 64 | tr -d '\n'`
      sed -i "s#'NONCE_KEY',.*#'NONCE_KEY', '$secret');#g" wp-config.php
      secret=`openssl rand -base64 64 | tr -d '\n'`
      sed -i "s#'AUTH_SALT',.*#'AUTH_SALT', '$secret');#g" wp-config.php
      secret=`openssl rand -base64 64 | tr -d '\n'`
      sed -i "s#'SECURE_AUTH_SALT',.*#'SECURE_AUTH_SALT', '$secret');#g" wp-config.php
      secret=`openssl rand -base64 64 | tr -d '\n'`
      sed -i "s#'LOGGED_IN_SALT',.*#'LOGGED_IN_SALT', '$secret');#g" wp-config.php
      secret=`openssl rand -base64 64 | tr -d '\n'`
      sed -i "s#'NONCE_SALT',.*#'NONCE_SALT', '$secret');#g" wp-config.php
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/wordpress"

  #######################
  ## initialise wordpress
  #######################
  - name: create site with admin user
    become: yes
    become_user: "{{pac}}-{{user}}"
    shell: |
      $HOME/bin/wp-cli.phar core install \
        --url='{{ domain }}' --title='{{ sitename }}' \
        --allow-root --no-color --path='/home/pacs/{{pac}}/users/{{user}}/wordpress' \
        --admin_name='{{ adminname }}' \
        --admin_email='{{ adminemail }}' \
        --admin_password='{{ adminpwd }}' || exit -1
      touch /home/pacs/{{pac}}/users/{{user}}/.wordpressinitialized
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/wordpress"
      creates: "/home/pacs/{{pac}}/users/{{user}}/.wordpressinitialized"

  #################################
  ## configure cronjobs
  #################################
  - name: setup cronjob for plugin and theme update
    # https://developer.wordpress.org/cli/commands/plugin/update/
    # https://developer.wordpress.org/cli/commands/theme/update/
    become: yes
    become_user: "{{pac}}-{{user}}"
    cron:
      name: "run wordpress plugin and theme updates"
      hour: "5"
      minute: "{{random_minute}}"
      job: "cd /home/pacs/{{pac}}/users/{{user}}/wordpress && ~/bin/wp-cli.phar plugin update --all && ~/bin/wp-cli.phar theme update --all"
